version: '3.9'
services:

  nginx:
    image: nginx:1.25.2-alpine
    container_name: nginx-acc
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "90:90"
    hostname: nginx-acc
    networks:
      - network1
    depends_on:
      - accounts-service-app
      - accounts-service-db
    restart: unless-stopped

  accounts-service-app:
    container_name: accounts-app
    image: manosov/accounts-minibank:latest
    build:
      context: ./
      dockerfile: Dockerfile_prod
    ports:
      - "9000:9000"
    depends_on:
      - accounts-service-db
    networks:
      - network1
    restart: unless-stopped

  accounts-service-db:
    container_name: accounts-db
    image: postgres:12
    ports:
      - "5434:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=user
    networks:
      - network1
    restart: unless-stopped
networks:
  network1:
    name: network1