version: '3.9'
services:

  nginx:
    image: nginx:1.25.2-alpine
    container_name: nginx-acc
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "90:90"
    hostname: nginx-acc
    networks:
      - network2
    depends_on:
      - accounts-app
      - accounts-db
    restart: unless-stopped

  accounts-app:
    container_name: accounts-app
    image: accounts-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - accounts-db
    networks:
      - network2
    restart: unless-stopped

  accounts-db:
    container_name: accounts-db
    image: accounts-db
    build:
      context: ./
      dockerfile: Dockerfile.postgres
    ports:
      - "5434:5434"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=user
    networks:
      - network2
    restart: unless-stopped
networks:
  network2:
    name: network2
    driver: bridge