features:
  accountCanCreate:
    name: "accountCanCreate"
    enabled: true
  accountCanDelete:
    name: "accountCanDelete"
    enabled: true
  accountCanUpdate:
    name: "accountCanUpdate"
    enabled: true
  accountCanGet:
    name: "accountCanGet"
    enabled: true
  accountsCanGet:
    name: "accountsCanGet"
    enabled: true